<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>59c87377-2cc0-4b1a-8159-53ca7cd90be6</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LeadRelay.Application\LeadRelay.Application.csproj" />
    <ProjectReference Include="..\LeadRelay.Infrastructure\LeadRelay.Infrastructure.csproj" />
    <ProjectReference Include="..\LeadRelay.Contracts\LeadRelay.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
