<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\LeadRelay.Application\LeadRelay.Application.csproj" />
    <ProjectReference Include="..\LeadRelay.Infrastructure\LeadRelay.Infrastructure.csproj" />
    <ProjectReference Include="..\LeadRelay.Contracts\LeadRelay.Contracts.csproj" />
  </ItemGroup>
</Project>
