<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="MySqlConnector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LeadRelay.Infrastructure\LeadRelay.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\LeadRelay.Web\LeadRelay.Web.csproj" />
  </ItemGroup>
</Project>
