<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeadRelay.Application\LeadRelay.Application.csproj" />
    <ProjectReference Include="..\LeadRelay.Domain\LeadRelay.Domain.csproj" />
  </ItemGroup>
</Project>
