<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LeadRelay.Application\LeadRelay.Application.csproj" />
    <ProjectReference Include="..\LeadRelay.Domain\LeadRelay.Domain.csproj" />
  </ItemGroup>
</Project>
